---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/ambv/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3.11
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.29.0
    hooks:
      - id: yamllint
      # args: [-c=/path/to/.yamllint]
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.0.1
    hooks:
      - id: autoflake
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-typing-imports==1.12.0]
  - repo: https://github.com/timothycrosley/isort
    rev: '5.12.0'  # Use the revision sha / tag you want to point at
    hooks:
      - id: isort
        additional_dependencies: [toml]
